### ISSUE TITLE
Add Talk: Integrating Machine Learning in Supply Chain Management

### ISSUE THREAD

**Issue by falknerdominik** [technologieplauscherl/technologieplauscherl.github.io#271]
Hi,

I could not create a PR / push a branch (no access). So here is the template for the next Plauscherl (including the talk). 

Talked with Dominik Hurnaus during the last Plauscherl.

```
---
title: "Technologieplauscherl LXXXIII"
permalink: /83/
name: 83
layout: post
datestring: "???"
timestring: "18:30"
startDateIso8601: ""
event:
  meetup:
  facebook:
pictures:
video:
location:
  name: ???
  address: ""
  city: Linz
  zip: 4040
  oldmap:
    lat: 48.317379
    lng: 14.289096
sponsor: <a href="INSERT">UNKNOWN</a>
speakers:
-
  name: "Dominik Falkner"
  talk: "Integrating Machine Learning in Supply Chain Management"
  img: /img/speaker_no_image.jpg
-
  name: "Someone"
  talk: "Talk 1"
  img: /img/speaker_no_image.jpg
-
  name: "Someone"
  talk: "Talk 2"
  img: /img/speaker_no_image.jpg
---
```
